### ISSUE TITLE
Site côté client : Quelle technologie est à utiliser ?

### ISSUE THREAD

**Issue by juridolfi** [cosnelle/projet-mobilite#7]
Pour le rendu du projet, nous allons faire un site qui présente les différents graphiques réalisés. 
Faut-il mieux le faire à l'aide de github [https://docs.github.com/fr/pages/quickstart](url) ou bien l'ouvrir à l'aide d'un terminal en local ?
L'API REST se lancera à partir d'un terminal.

**Comment by damienmarchal** [comment]
Vu le temps restant d'ici la fin du projet, faites tout en local. 
En terme de déployement, 
Je dirais: d'un serveru web de test avec python3 -m http.server (sur un port donné) et de l'autre l'API rest sur un autre port.
A moins que FAST-API ne permette de créer des routes vers le serveur de fichier facilement.
